base_url = "https://newton.cx/~peter/"
title = "PKGW"
default_language = "en"
compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml"]
build_search_index = false

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
github_base = "https://github.com/pkgw/website"
